title: Flying through the clouds
author: marinaconsa
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal blog. I'll be writing about me and my dreams.
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
